const RequiredPermission = {
    CENTRALIZARE_VIEW_LIVE : "CENTRALIZARE_VIEW_LIVE",
    CENTRALIZARE_EDIT_LIVE : "CENTRALIZARE_EDIT_LIVE",
    
    CENTRALIZARE_VIEW : "CENTRALIZARE_VIEW",
    CENTRALIZARE_EDIT : "CENTRALIZARE_EDIT",

    CLIENT_VIEW : "CLIENT_VIEW",
    CLIENT_EDIT : "CLIENT_EDIT",

    CONTACTE_VIEW : "CONTACTE_VIEW",
    CONTACTE_EDIT : "CONTACTE_EDIT",
}