const ContacteStatusFilterSupplier = filterName => {
    const {
        NESUNAT,

        NURASPUNDE1,
        NURASPUNDE2,
        NURASPUNDE3,

        REVINPESTE,
        REVINEELEA,

        REFUZTELEFON,
        NRINVALID,
        NRNECUNOSCUT,
        DEJACLIENT,

        ANALIZA,
        CONSULTANTA,
        CONTRACT,

        NUMAIRASPUNDE,
        ABSENTINTALNIRE,
        REFUZOFERTA,

        DEREPROGRAMATINTALNIRE,
        REVINCUOFERTAPANA,

        POTENTIALCLIENT,
        POTENTIALCOLABORATOR,
        POTENTIALRECOMANDATOR,

        CLIENT,
        SERVICE,
        CLIENTPIERDUT,

        ABANDONEZ,

        REVINPESTEDINOU,
        REVINEELEADINNOU,

        REPROGRAMEAZAANALIZA,
        REPROGRAMEAZACONSULTANTA,
        REPROGRAMEAZACONTRACT,
        REPROGRAMEAZASERVICE,

        PROGRAMEAZAINTALNIRE,
    } = ContacteStatus;
    // [NESUNAT, NURASPUNDE1, NURASPUNDE2, NURASPUNDE3, REVINPESTE, REVINEELEA, REFUZTELEFON, NRINVALID, NRNECUNOSCUT, DEJACLIENT, ANALIZA, CONSULTANTA, CONTRACT, NUMAIRASPUNDE, ABSENTINTALNIRE, REFUZOFERTA, DEREPROGRAMATINTALNIRE, REVINCUOFERTAPANA, POTENTIALCLIENT, POTENTIALCOLABORATOR, POTENTIALRECOMANDATOR, CLIENT, SERVICE, CLIENTPIERDUT, ABANDONEZ, RESETEZSTATUSUL, REVINPESTEDINOU, REVINEELEADINNOU, REPROGRAMEAZAANALIZA, REPROGRAMEAZACONSULTANTA, REPROGRAMEAZACONTRACT, REPROGRAMEAZASERVICE];
    switch (filterName) {
        case ContacteStatusFilters.SHORTLIST: return [NURASPUNDE3, REFUZTELEFON, NRINVALID, NRNECUNOSCUT, DEJACLIENT, NUMAIRASPUNDE, ABSENTINTALNIRE, REFUZOFERTA, DEREPROGRAMATINTALNIRE];
        case ContacteStatusFilters.PROGARMARI: return [NESUNAT, NURASPUNDE1, NURASPUNDE2, NURASPUNDE3, REVINPESTE, REVINEELEA, REFUZTELEFON, NRINVALID, NRNECUNOSCUT, DEJACLIENT, NUMAIRASPUNDE, ABSENTINTALNIRE, REFUZOFERTA, DEREPROGRAMATINTALNIRE, REVINCUOFERTAPANA, POTENTIALCLIENT, POTENTIALCOLABORATOR, POTENTIALRECOMANDATOR, CLIENT, SERVICE, CLIENTPIERDUT, ABANDONEZ, REVINPESTEDINOU, REVINEELEADINNOU];
        case ContacteStatusFilters.OPORTUNI: return [NESUNAT, NURASPUNDE1, NURASPUNDE2, NURASPUNDE3, REVINPESTE, REVINEELEA, REFUZTELEFON, NRINVALID, NRNECUNOSCUT, DEJACLIENT, ANALIZA, CONSULTANTA, CONTRACT, NUMAIRASPUNDE, ABSENTINTALNIRE, REFUZOFERTA, DEREPROGRAMATINTALNIRE, CLIENT, SERVICE, CLIENTPIERDUT, ABANDONEZ, REVINPESTEDINOU, REVINEELEADINNOU, REPROGRAMEAZAANALIZA, REPROGRAMEAZACONSULTANTA, REPROGRAMEAZACONTRACT, REPROGRAMEAZASERVICE];;
        case ContacteStatusFilters.CLIENTI: return [NESUNAT, NURASPUNDE1, NURASPUNDE2, NURASPUNDE3, REVINPESTE, REVINEELEA, REFUZTELEFON, NRINVALID, NRNECUNOSCUT, DEJACLIENT, ANALIZA, CONSULTANTA, CONTRACT, NUMAIRASPUNDE, ABSENTINTALNIRE, REFUZOFERTA, DEREPROGRAMATINTALNIRE, REVINCUOFERTAPANA, POTENTIALCLIENT, POTENTIALCOLABORATOR, POTENTIALRECOMANDATOR, ABANDONEZ, REVINPESTEDINOU, REVINEELEADINNOU, REPROGRAMEAZAANALIZA, REPROGRAMEAZACONSULTANTA, REPROGRAMEAZACONTRACT, REPROGRAMEAZASERVICE];
        case ContacteStatusFilters.REMINDERE: return [NESUNAT, NURASPUNDE1, NURASPUNDE2, NURASPUNDE3, REFUZTELEFON, NRINVALID, NRNECUNOSCUT, DEJACLIENT, NUMAIRASPUNDE, ABSENTINTALNIRE, REFUZOFERTA, DEREPROGRAMATINTALNIRE, CLIENT, CLIENTPIERDUT, ABANDONEZ];
        case ContacteStatusFilters.STERGE_FILTRU: return null;
        default: Lug.warning(`Contacte status filter {${filterName}} could not be found.`); return null;
    }
}