const ContateStatusValidationSupplier = statusValue => {
  const {
    NESUNAT,
    NURASPUNDE1,
    NURASPUNDE2,
    NURASPUNDE3,
    REVINPESTE,
    REVINEELEA,
    REFUZTELEFON,
    NRINVALID,
    NRNECUNOSCUT,
    DEJACLIENT,
    ANALIZA,
    CONSULTANTA,
    CONTRACT,
    NUMAIRASPUNDE,
    ABSENTINTALNIRE,
    REFUZOFERTA,
    DEREPROGRAMATINTALNIRE,
    REVINCUOFERTAPANA,
    POTENTIALCLIENT,
    POTENTIALCOLABORATOR,
    POTENTIALRECOMANDATOR,
    SERVICE,
    CLIENT,
    CLIENTPIERDUT,
    ABANDONEZ,
    RESETEZSTATUSUL,
    REVINPESTEDINOU,
    REVINEELEADINNOU,
    REPROGRAMEZANALIZA,
    REPROGRAMEZCONSULTANTA,
    REPROGRAMEZCONTRACT,
    REPROGRAMEZSERVICE,
    PROGRAMEAZAINTALNIRE
  } = ContacteStatus;

  switch (statusValue) {
    case NESUNAT: return [NESUNAT, PROGRAMEAZAINTALNIRE, NURASPUNDE1, REVINPESTE, REVINEELEA, REFUZTELEFON, NRINVALID, NRNECUNOSCUT, DEJACLIENT, ABANDONEZ];

    case NURASPUNDE1: return [NURASPUNDE1, PROGRAMEAZAINTALNIRE, NURASPUNDE2, REVINPESTE, REVINEELEA, REFUZTELEFON, NRNECUNOSCUT, DEJACLIENT, ANALIZA, ABANDONEZ];
    case NURASPUNDE2: return [NURASPUNDE2, PROGRAMEAZAINTALNIRE, NURASPUNDE3, REVINPESTE, REVINEELEA, REFUZTELEFON, NRNECUNOSCUT, DEJACLIENT, ANALIZA, ABANDONEZ];
    case NURASPUNDE3: return [NURASPUNDE3, PROGRAMEAZAINTALNIRE, REVINPESTE, REVINEELEA, REFUZTELEFON, NRNECUNOSCUT, DEJACLIENT, ABANDONEZ];

    case REVINPESTE: return [REVINPESTE, PROGRAMEAZAINTALNIRE, REVINPESTEDINOU, REFUZTELEFON, REVINEELEA, NUMAIRASPUNDE, ABANDONEZ];
    case REVINEELEA: return [REVINEELEA, PROGRAMEAZAINTALNIRE, REVINEELEADINNOU, REFUZTELEFON, REVINPESTE, NUMAIRASPUNDE, ABANDONEZ];

    case REVINPESTEDINOU: return [REVINPESTE, PROGRAMEAZAINTALNIRE, REVINPESTEDINOU, REFUZTELEFON, REVINEELEA, NUMAIRASPUNDE, ABANDONEZ];
    case REVINEELEADINNOU: return [REVINEELEA, PROGRAMEAZAINTALNIRE, REVINEELEADINNOU, REFUZTELEFON, REVINPESTE, NUMAIRASPUNDE, ABANDONEZ];

    case REFUZTELEFON: return [REFUZTELEFON, PROGRAMEAZAINTALNIRE];
    case NRINVALID: return [NRINVALID, PROGRAMEAZAINTALNIRE, REFUZTELEFON, NUMAIRASPUNDE, ];
    case NRNECUNOSCUT: return [NRNECUNOSCUT, PROGRAMEAZAINTALNIRE, REFUZTELEFON, DEJACLIENT, ABANDONEZ];
    case DEJACLIENT: return [DEJACLIENT, PROGRAMEAZAINTALNIRE, RESETEZSTATUSUL];

    case ANALIZA: return [ANALIZA, PROGRAMEAZAINTALNIRE, NUMAIRASPUNDE, ABSENTINTALNIRE, REFUZOFERTA, DEREPROGRAMATINTALNIRE, REVINCUOFERTAPANA, POTENTIALCLIENT, POTENTIALCOLABORATOR, POTENTIALRECOMANDATOR, ABANDONEZ];
    case CONSULTANTA: return [CONSULTANTA, REPROGRAMEZCONSULTANTA, NUMAIRASPUNDE, ABSENTINTALNIRE, REFUZOFERTA, CONTRACT, DEREPROGRAMATINTALNIRE, REVINCUOFERTAPANA, POTENTIALCLIENT, POTENTIALCOLABORATOR, POTENTIALRECOMANDATOR, ABANDONEZ];
    case CONTRACT: return [CONTRACT, REPROGRAMEZCONTRACT, NUMAIRASPUNDE, ABSENTINTALNIRE, REFUZOFERTA, CLIENT, DEREPROGRAMATINTALNIRE, REVINCUOFERTAPANA, POTENTIALCLIENT, POTENTIALCOLABORATOR, POTENTIALRECOMANDATOR, ABANDONEZ];

    case REPROGRAMEZANALIZA: return [ANALIZA, PROGRAMEAZAINTALNIRE, NUMAIRASPUNDE, ABSENTINTALNIRE, REFUZOFERTA, CONSULTANTA, DEREPROGRAMATINTALNIRE, REVINCUOFERTAPANA, POTENTIALCLIENT, POTENTIALCOLABORATOR, POTENTIALRECOMANDATOR, ABANDONEZ];
    case REPROGRAMEZCONSULTANTA: return [CONSULTANTA, PROGRAMEAZAINTALNIRE, NUMAIRASPUNDE, ABSENTINTALNIRE, REFUZOFERTA, CONTRACT, DEREPROGRAMATINTALNIRE, REVINCUOFERTAPANA, POTENTIALCLIENT, POTENTIALCOLABORATOR, POTENTIALRECOMANDATOR, ABANDONEZ];
    case REPROGRAMEZCONTRACT: return [CONTRACT, PROGRAMEAZAINTALNIRE, NUMAIRASPUNDE, ABSENTINTALNIRE, REFUZOFERTA, CLIENT, DEREPROGRAMATINTALNIRE, REVINCUOFERTAPANA, POTENTIALCLIENT, POTENTIALCOLABORATOR, POTENTIALRECOMANDATOR, ABANDONEZ];

    case NUMAIRASPUNDE: return [NUMAIRASPUNDE, PROGRAMEAZAINTALNIRE, DEREPROGRAMATINTALNIRE, ABANDONEZ];
    case ABSENTINTALNIRE: return [ABSENTINTALNIRE, PROGRAMEAZAINTALNIRE, NUMAIRASPUNDE, REFUZOFERTA, DEREPROGRAMATINTALNIRE, ABANDONEZ];
    case REFUZOFERTA: return [REFUZOFERTA, PROGRAMEAZAINTALNIRE, POTENTIALCLIENT, POTENTIALCOLABORATOR, POTENTIALRECOMANDATOR, ABANDONEZ];

    case DEREPROGRAMATINTALNIRE: return [DEREPROGRAMATINTALNIRE, PROGRAMEAZAINTALNIRE, NUMAIRASPUNDE, REFUZOFERTA, ABANDONEZ];
    case REVINCUOFERTAPANA: return [REVINCUOFERTAPANA, PROGRAMEAZAINTALNIRE, NUMAIRASPUNDE, POTENTIALCLIENT, POTENTIALCOLABORATOR, POTENTIALRECOMANDATOR, REFUZOFERTA, ABANDONEZ, RESETEZSTATUSUL];

    case SERVICE: return [SERVICE, PROGRAMEAZAINTALNIRE, CLIENT, CLIENTPIERDUT, RESETEZSTATUSUL];
    case CLIENT: return [CLIENT, PROGRAMEAZAINTALNIRE, DEREPROGRAMATINTALNIRE, CLIENTPIERDUT, POTENTIALCOLABORATOR, REFUZOFERTA];
    case CLIENTPIERDUT: return [CLIENTPIERDUT, PROGRAMEAZAINTALNIRE, CLIENT, RESETEZSTATUSUL];

    case POTENTIALCLIENT: return [POTENTIALCLIENT, PROGRAMEAZAINTALNIRE, NUMAIRASPUNDE, POTENTIALCOLABORATOR, POTENTIALRECOMANDATOR, REFUZOFERTA, ABANDONEZ, RESETEZSTATUSUL];
    case POTENTIALCOLABORATOR: return [POTENTIALCOLABORATOR, PROGRAMEAZAINTALNIRE, NUMAIRASPUNDE, REFUZOFERTA, POTENTIALCLIENT, POTENTIALRECOMANDATOR, ABANDONEZ, RESETEZSTATUSUL];
    case POTENTIALRECOMANDATOR: return [POTENTIALCLIENT, POTENTIALCOLABORATOR, PROGRAMEAZAINTALNIRE, NUMAIRASPUNDE, REFUZOFERTA, ABANDONEZ, RESETEZSTATUSUL];

    // case colaborator

    case ABANDONEZ: return [ABANDONEZ, PROGRAMEAZAINTALNIRE];
  }
}