const ContateStatusValidationSupplier = statusValue => {
    const {
      NESUNAT,
      NURASPUNDE1,
      NURASPUNDE2,
      NURASPUNDE3,
      REVINPESTE,
      REVINEELEA,
      REFUZTELEFON,
      NRINVALID,
      NRNECUNOSCUT,
      DEJACLIENT,
      ANALIZA,
      CONSULTANTA,
      CONTRACT,
      NUMAIRASPUNDE,
      ABSENTINTALNIRE,
      REFUZOFERTA,
      DEREPROGRAMATINTALNIRE,
      REVINCUOFERTAPANA,
      POTENTIALCLIENT,
      POTENTIALCOLABORATOR,
      POTENTIALRECOMANDATOR,
      SERVICE,
      CLIENT,
      CLIENTPIERDUT,
      ABANDONEZ,
      RESETEZSTATUSUL
    } = ContacteStatus;

    switch (statusValue) {
      case NESUNAT: return [NESUNAT, NURASPUNDE1, REVINPESTE, REVINEELEA, REFUZTELEFON, NRINVALID, NRNECUNOSCUT, DEJACLIENT, ANALIZA, ABANDONEZ, RESETEZSTATUSUL];

      case NURASPUNDE1: return [NURASPUNDE1, NURASPUNDE2, REVINPESTE, REVINEELEA, REFUZTELEFON, NRNECUNOSCUT, DEJACLIENT, ANALIZA, ABANDONEZ, RESETEZSTATUSUL];
      case NURASPUNDE2: return [NURASPUNDE2, NURASPUNDE3, REVINPESTE, REVINEELEA, REFUZTELEFON, NRNECUNOSCUT, DEJACLIENT, ANALIZA, ABANDONEZ, RESETEZSTATUSUL];
      case NURASPUNDE3: return [NURASPUNDE3, REVINPESTE, REVINEELEA, REFUZTELEFON, NRNECUNOSCUT, DEJACLIENT, ANALIZA, ABANDONEZ, RESETEZSTATUSUL];

      case REVINPESTE: return [REVINPESTE, "RevinPesteDinNou", REFUZTELEFON, REVINEELEA, ANALIZA, NUMAIRASPUNDE, ABANDONEZ, RESETEZSTATUSUL];
      case REVINEELEA: return [REVINEELEA, REFUZTELEFON, REVINPESTE, ANALIZA, NUMAIRASPUNDE, ABANDONEZ, RESETEZSTATUSUL];

      case REFUZTELEFON: return [REFUZTELEFON, ANALIZA, RESETEZSTATUSUL];
      case NRINVALID: return [NRINVALID, RESETEZSTATUSUL];
      case NRNECUNOSCUT: return [NRNECUNOSCUT, REFUZTELEFON, DEJACLIENT, ANALIZA, ABANDONEZ, RESETEZSTATUSUL];
      case DEJACLIENT: return [DEJACLIENT, RESETEZSTATUSUL];

      case ANALIZA: return [ANALIZA, "ReprogrameazaAnaliza", NUMAIRASPUNDE, ABSENTINTALNIRE, REFUZOFERTA, CONSULTANTA, DEREPROGRAMATINTALNIRE, REVINCUOFERTAPANA, POTENTIALCLIENT, POTENTIALCOLABORATOR, POTENTIALRECOMANDATOR, ABANDONEZ, RESETEZSTATUSUL];
      case CONSULTANTA: return [CONSULTANTA, "ReprogrameazaConsultanta", NUMAIRASPUNDE, ABSENTINTALNIRE, REFUZOFERTA, CONTRACT, DEREPROGRAMATINTALNIRE, REVINCUOFERTAPANA, POTENTIALCLIENT, POTENTIALCOLABORATOR, POTENTIALRECOMANDATOR, ABANDONEZ, RESETEZSTATUSUL];
      case CONTRACT: return [CONTRACT, "ReprogrameazaContract", NUMAIRASPUNDE, ABSENTINTALNIRE, REFUZOFERTA, CLIENT, DEREPROGRAMATINTALNIRE, REVINCUOFERTAPANA, POTENTIALCLIENT, POTENTIALCOLABORATOR, POTENTIALRECOMANDATOR, ABANDONEZ, RESETEZSTATUSUL];

      case NUMAIRASPUNDE: return [NUMAIRASPUNDE, ANALIZA, CONSULTANTA, CONTRACT, DEREPROGRAMATINTALNIRE, ABANDONEZ, RESETEZSTATUSUL];
      case ABSENTINTALNIRE: return [ABSENTINTALNIRE, ANALIZA, CONSULTANTA, CONTRACT, NUMAIRASPUNDE, REFUZOFERTA, DEREPROGRAMATINTALNIRE, ABANDONEZ, RESETEZSTATUSUL];
      case REFUZOFERTA: return [REFUZOFERTA, CONSULTANTA, CONTRACT, POTENTIALCLIENT, POTENTIALCOLABORATOR, POTENTIALRECOMANDATOR, ABANDONEZ, RESETEZSTATUSUL];

      case DEREPROGRAMATINTALNIRE: return [DEREPROGRAMATINTALNIRE, ANALIZA, CONSULTANTA, CONTRACT, NUMAIRASPUNDE, REFUZOFERTA, ABANDONEZ, RESETEZSTATUSUL];
      case REVINCUOFERTAPANA: return [REVINCUOFERTAPANA, CONSULTANTA, CONTRACT, NUMAIRASPUNDE, POTENTIALCLIENT, POTENTIALCOLABORATOR, POTENTIALRECOMANDATOR, REFUZOFERTA, ABANDONEZ, RESETEZSTATUSUL];

      case SERVICE: return [SERVICE, "ReprogrameazaService", CLIENT, CONTRACT, CLIENTPIERDUT, RESETEZSTATUSUL];
      case CLIENT: return [CLIENT, SERVICE, DEREPROGRAMATINTALNIRE, CLIENTPIERDUT, POTENTIALCOLABORATOR, REFUZOFERTA, RESETEZSTATUSUL];
      case CLIENTPIERDUT: return [CLIENTPIERDUT, CLIENT, CONTRACT, SERVICE, RESETEZSTATUSUL];

      case POTENTIALCLIENT: return [POTENTIALCLIENT, CONSULTANTA, CONTRACT, NUMAIRASPUNDE, POTENTIALCOLABORATOR, POTENTIALRECOMANDATOR, REFUZOFERTA, ABANDONEZ, RESETEZSTATUSUL];
      case POTENTIALCOLABORATOR: return [POTENTIALCOLABORATOR, ANALIZA, CONSULTANTA, CONTRACT, SERVICE, NUMAIRASPUNDE, REFUZOFERTA, POTENTIALCLIENT, POTENTIALRECOMANDATOR, ABANDONEZ, RESETEZSTATUSUL];
      case POTENTIALRECOMANDATOR: return [POTENTIALCLIENT, POTENTIALCOLABORATOR, ANALIZA, CONSULTANTA, CONTRACT, SERVICE, NUMAIRASPUNDE, REFUZOFERTA, ABANDONEZ, RESETEZSTATUSUL];

      case ABANDONEZ: return [ABANDONEZ, RESETEZSTATUSUL];
      // case RESETEZSTATUSUL: return resetStatus();

      
      // default: return SpreadshDeetApp.newDataValidation().requireValueInList([value, RESETEZSTATUSUL]).setAllowInvalid(false).build();
    }
  }